INSERT INTO "C##DMRVAL"."GENDER" (GENDERID, GENDERNAME) VALUES ('1', 'MR');
INSERT INTO "C##DMRVAL"."GENDER" (GENDERID, GENDERNAME) VALUES ('2', 'MRS');


INSERT INTO "C##DMRVAL"."ROLES" (ROLEID, ROLENAME) VALUES ('1', 'USER');
INSERT INTO "C##DMRVAL"."ROLES" (ROLEID, ROLENAME) VALUES ('2', 'GUEST');


INSERT INTO "C##DMRVAL"."USERS" (USERID, FULLNAME, ADDRESS, LOGIN, PASSWORD, GENDER, ROLE) VALUES ('1', 'Justin Perkins', '5779 Pockrus Page Rd', 'walton', 'walton', '1', '1');
INSERT INTO "C##DMRVAL"."USERS" (USERID, FULLNAME, ADDRESS, LOGIN, PASSWORD, GENDER, ROLE) VALUES ('2', 'Edith Duncan', '1254 W Gray St', 'disney1', 'disney1', '2', '1');
INSERT INTO "C##DMRVAL"."USERS" (USERID, FULLNAME, ADDRESS, LOGIN, PASSWORD, GENDER, ROLE) VALUES ('3', 'Howard Olson', '1245 Nowlin Rd', 'chriss', 'chriss', '1', '1');
INSERT INTO "C##DMRVAL"."USERS" (USERID, FULLNAME, ADDRESS, LOGIN, PASSWORD, GENDER, ROLE) VALUES ('4', 'Mia Weaver', '2852 White Oak Dr', 'markus', 'markus', '2', '1');
INSERT INTO "C##DMRVAL"."USERS" (USERID, FULLNAME, ADDRESS, LOGIN, PASSWORD, GENDER, ROLE) VALUES ('5', 'Joel Carr', '3425 Oak Ridge Ln', 'frogman', 'frogman', '1', '1');

INSERT INTO "C##DMRVAL"."BIDDER" (BIDDERID, BIDDEROFFER, BIDDERUSER_FK) VALUES ('1', '2000', '5');

INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('1', '1000', '100', TO_TIMESTAMP('2019-10-05 15:09:24.773000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '1');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('2', '1100', '80', TO_TIMESTAMP('2019-10-30 15:10:10.116000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '1');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('3', '2400', '600', TO_TIMESTAMP('2019-10-31 15:10:29.237000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '2', '1');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('4', '700', '20', TO_TIMESTAMP('2019-10-31 15:10:47.990000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '2', '0');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('5', '1900', '190', TO_TIMESTAMP('2019-10-24 15:11:33.996000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '3', '1');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL,BIDDER_FK, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('6', '19000', '1000','1', TO_TIMESTAMP('2019-10-23 15:12:27.093000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '4', '1');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('7', '8000', '500', TO_TIMESTAMP('2019-11-15 15:12:47.925000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '5', '1');
INSERT INTO "C##DMRVAL"."AUCTIONPRODUCTINFO" (INFOID, STARTPRICE, STEPLEVEL, TIME, USER_MASTER_FK, ISBIDDING) VALUES ('8', '1010', '10', TO_TIMESTAMP('2019-10-31 15:13:08.797000000', 'YYYY-MM-DD HH24:MI:SS.FF'), '5', '0');


INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('1', 'Monitor', 'a device for reproducing a video signal and visual display of information', '6');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('2', 'HDD', 'memory devices', '7');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('3', 'RAM', 'volatile part of computer memory system', '3');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('4', 'Drive', 'computer device that allows reading and writing information', '2');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('5', 'Solid state drive', 'non-volatile non-mechanical computer memory based on memory chips', '5');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('6', 'Keyboard', 'a set of keys arranged in a certain order to control a device or to enter data', '4');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('7', 'Headphones', 'device for personal listening to music', '1');
INSERT INTO "C##DMRVAL"."PRODUCTS" (PRODUCTID, NAMEPRODUCT, DESCRIPTION, AUCTIONINFO_FK) VALUES ('8', 'Webcam', 'real-time digital video or camera', '8');

commit ;


